import { isElasticsearchEnabled } from '@/lib/search/elasticsearch';
import { isOllamaEnabled } from '@/lib/ai/ollama';
import { isQdrantEnabled } from '@/lib/ai/qdrant';
import { isClaudeEnabled } from '@/lib/ai/claude';
import { isGeminiEnabled } from '@/lib/ai/gemini';
import { getMemoryStore } from '@/lib/ai/memory';

export interface ServiceHealthStatus {
  name: string;
  enabled: boolean;
  healthy: boolean;
  detail: string;
}

export interface AiInfrastructureStatus {
  ok: boolean;
  readyForIngest: boolean;
  readyForChat: boolean;
  services: ServiceHealthStatus[];
}

async function probeService(url: string): Promise<{ ok: boolean; detail: string }> {
  try {
    const response = await fetch(url, { method: 'GET' });
    const bodyText = await response.text().catch(() => '');
    return {
      ok: response.ok,
      detail: response.ok ? 'reachable' : `${response.status} ${bodyText}`.trim(),
    };
  } catch (error) {
    return {
      ok: false,
      detail: error instanceof Error ? error.message : 'request failed',
    };
  }
}

export async function getAiInfrastructureStatus(): Promise<AiInfrastructureStatus> {
  const ollamaUrl = process.env.OLLAMA_URL;
  const qdrantUrl = process.env.QDRANT_URL;
  const elasticsearchUrl = process.env.ELASTICSEARCH_URL;
  const embeddingServiceUrl = process.env.EMBEDDING_SERVICE_URL;

  const services: ServiceHealthStatus[] = [];

  const ollamaProbe = ollamaUrl
    ? await probeService(`${ollamaUrl.replace(/\/$/, '')}/api/tags`)
    : { ok: false, detail: 'OLLAMA_URL is not configured' };

  if (isOllamaEnabled() && ollamaUrl) {
    services.push({
      name: 'ollama',
      enabled: true,
      healthy: ollamaProbe.ok,
      detail: ollamaProbe.ok ? 'Ollama is reachable' : ollamaProbe.detail,
    });
  } else {
    services.push({
      name: 'ollama',
      enabled: false,
      healthy: false,
      detail: ollamaProbe.detail,
    });
  }

  if (isQdrantEnabled() && qdrantUrl) {
    const probe = await probeService(`${qdrantUrl.replace(/\/$/, '')}/collections`);
    services.push({
      name: 'qdrant',
      enabled: true,
      healthy: probe.ok,
      detail: probe.ok ? 'Qdrant is reachable' : probe.detail,
    });
  } else {
    services.push({
      name: 'qdrant',
      enabled: false,
      healthy: false,
      detail: 'QDRANT_URL is not configured',
    });
  }

  if (isElasticsearchEnabled() && elasticsearchUrl) {
    const probe = await probeService(`${elasticsearchUrl.replace(/\/$/, '')}/_cluster/health`);
    services.push({
      name: 'elasticsearch',
      enabled: true,
      healthy: probe.ok,
      detail: probe.ok ? 'Elasticsearch is reachable' : probe.detail,
    });
  } else {
    services.push({
      name: 'elasticsearch',
      enabled: false,
      healthy: false,
      detail: 'ELASTICSEARCH_URL is not configured',
    });
  }

  if (embeddingServiceUrl) {
    const probe = await probeService(`${embeddingServiceUrl.replace(/\/$/, '')}/health`);
    services.push({
      name: 'embedding-service',
      enabled: true,
      healthy: probe.ok,
      detail: probe.ok ? 'Embedding service is reachable' : probe.detail,
    });
  } else if (isOllamaEnabled() && ollamaUrl) {
    services.push({
      name: 'embedding-service',
      enabled: true,
      healthy: ollamaProbe.ok,
      detail: ollamaProbe.ok
        ? 'Embeddings are generated by Ollama'
        : `Ollama embeddings unavailable (${ollamaProbe.detail})`,
    });
  } else if (isGeminiEnabled()) {
    services.push({
      name: 'embedding-service',
      enabled: true,
      healthy: true,
      detail: 'Embeddings are generated by Gemini',
    });
  } else {
    services.push({
      name: 'embedding-service',
      enabled: false,
      healthy: false,
      detail: 'EMBEDDING_SERVICE_URL is not configured (set it, or set OLLAMA_URL or GEMINI_API_KEY for embeddings)',
    });
  }

  if (isClaudeEnabled()) {
    services.push({ name: 'claude', enabled: true, healthy: true, detail: 'Claude API key is configured' });
  } else {
    services.push({ name: 'claude', enabled: false, healthy: false, detail: 'CLAUDE_API_KEY is not configured' });
  }

  if (isGeminiEnabled()) {
    services.push({ name: 'gemini', enabled: true, healthy: true, detail: 'Gemini API key is configured' });
  } else {
    services.push({ name: 'gemini', enabled: false, healthy: false, detail: 'GEMINI_API_KEY is not configured' });
  }

  const readyForIngest = services.some((service) => service.name === 'qdrant' && service.healthy)
    || services.some((service) => service.name === 'elasticsearch' && service.healthy);

  const readyForChat = services.some((service) => service.name === 'ollama' && service.healthy)
    || services.some((service) => service.name === 'gemini' && service.healthy)
    || services.some((service) => service.name === 'claude' && service.healthy);

  try {
    const memoryStore = await getMemoryStore();
    services.push({
      name: 'memory',
      enabled: true,
      healthy: true,
      detail: memoryStore.backend === 'redis' ? 'Redis-backed chat memory' : 'In-memory chat memory (Redis not connected)',
    });
  } catch (error) {
    services.push({
      name: 'memory',
      enabled: false,
      healthy: false,
      detail: error instanceof Error ? error.message : 'Chat memory unavailable',
    });
  }

  return { ok: readyForChat, readyForIngest, readyForChat, services };
}
